### ISSUE TITLE
makeSuite removed in Python3.13

### ISSUE THREAD

**Issue by stefanor** [scoder/acora#25]
```
$ python3.13 test.py
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.13_acora/build/test.py", line 456, in <module>
    unittest.TextTestRunner(verbosity=verbosity).run(suite())
                                                     ~~~~~^^
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.13_acora/build/test.py", line 443, in suite
    unittest.makeSuite(UnicodeAcoraTest),
    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/__init__.py", line 80, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}") 
AttributeError: module 'unittest' has no attribute 'makeSuite'
```

https://docs.python.org/3.13/whatsnew/3.13.html#unittest

**Comment by scoder** [comment]
Thanks. Fixed in https://github.com/scoder/acora/commit/c630d96c60e4fed870560e3cdbd95a2a0da49377
